### ISSUE TITLE
Mailchimp

### ISSUE THREAD

**Issue by aschwersenz** [ushahidi/opensourcedesign#15]
Do we want to use Mailchimp for collecting the user sign ups? Do you already have an MC account that we can use?

**Comment by aschwersenz** [comment]
from Justin: Not sure yet whether we want to use MC or some other service. Double checking with team.

**Comment by aschwersenz** [comment]
from Jay: Yes, MC would be my preferred candidate for outbound communication (we can also offload much of the GDPR compliance to them), and allows for proper segmentation of contact lists and even demographics (with a certain level of $$).

Keep in mind it is not a CRM, which brings us back to the abstraction layer to Github.

**Comment by aschwersenz** [comment]
from Eriol: I would prefer to use Mail chimp too - this doesn't need to integrate with Ushahidi systems fully

**Comment by aschwersenz** [comment]
from Eriol: Doesn't mail chimp have a fee for over a certain amount of people on a mailing list though?

**Comment by aschwersenz** [comment]
from Jay: MC fee is for mailing lists of >2000 people, and then it is per email/contact (a points system) and rather affordable.

One (but not the primary) reason for clustering the contacts we gather into various areas of interest == lists.

**Comment by justinscherer** [comment]
- [ ] Create a Mailchimp account (free for now), and we'll upgrade later if need be.

**Comment by Erioldoesdesign** [comment]
This Mailchimp account has been created and tied to our wordpress site
