### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by aschwersenz** [ushahidi/opensourcedesign#16]
What about tracking, e.g. Google Analytics?

**Comment by aschwersenz** [comment]
from Justin: GA should be integrated, yes. Not sure if we use our pre-existing account or not. Will follow up with team.

**Comment by aschwersenz** [comment]
from Jay: GA is a different animal and I agree

**Comment by aschwersenz** [comment]
from Jay: GA: if there is reason to avoid GA, Piwik is a proven and powerful alternative.

**Comment by aschwersenz** [comment]
from Jay: Matomo, the artist formerly known as Piwik, I mean. :slightly_smiling_face: https://piwik.com/

**Comment by justinscherer** [comment]
cc @rowasc How can we integrate this into our GA instance? Should we?

**Comment by rowasc** [comment]
sorry, what's the page that we need to/are thinking of  integrating? 
@justinscherer

**Comment by justinscherer** [comment]
@rowasc the information page for the open source design project. We'll want to track traffic, etc. Wondering if it makes sense to run it through our GA account, or to create a new one.

**Comment by rowasc** [comment]
ah, ok makes sense.
I think it should be the same account, just a different project in the same GA account then

**Comment by justinscherer** [comment]
How / who would put that together?

**Comment by rowasc** [comment]
Assuming someone can put in the GA Code in the code (is Anna working on it? ) , I could set you up in analytics .

**Comment by rowasc** [comment]
It's 2 steps basically, creating the GA property (me) and then putting in the GA code in the HTML(someone/me/?)

**Comment by justinscherer** [comment]
@rowasc can you send @aschwersenz the code in this issue when you've got it done?

**Comment by rowasc** [comment]
Yep, can you send me the URL ? Analytics asks for it to register the property  (it can be a temporary one)

**Comment by justinscherer** [comment]
opendesign.ushahidi.com

**Comment by rowasc** [comment]
@aschwersenz UA-12063676-40
This is the UA code to add :)

**Comment by rowasc** [comment]
```
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-12063676-40"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-12063676-40');
</script>

```

**Comment by Erioldoesdesign** [comment]
@aschwersenz GA code

**Comment by Erioldoesdesign** [comment]
GA is on the website and Joy is now on our GA account. Closing!
