### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by aschwersenz** [ushahidi/opensourcedesign#19]
HTTPS would be amazing, also because users can sign up on the page. So somebody has to take care of getting a https certificate?

**Comment by justinscherer** [comment]
cc @tuxpiper @mackers Can you provide some guidance here?

**Comment by tuxpiper** [comment]
HTTPS is actually a must nowadays :) There are even some top level domains (i.e. .dev) that are assumed  to have it or show warnings in users browsers.

The exact approach largely depends on the hosting decision (#14) . Most maintainable thing in the long run would be for the hosting provider to facilitate / provide this.

**Comment by Erioldoesdesign** [comment]
@tuxpiper Is this covered by Bluehost? Assuming yes but can you drop a confirmation comment and close this ticket please?

**Comment by tuxpiper** [comment]
Yep this is taken care of by Bluehost . Can close.
