### ISSUE TITLE
Social media accounts

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/opensourcedesign#22]
- [x] Choose which SM networks we want to use
- [x] Sign up for the social media accounts
- [x] Make sure the team has the right credentials and passwords

**Comment by thesocialdetail** [comment]
Facebook page and Twitter account created.

**Comment by thesocialdetail** [comment]
- [ ] 1080 by 1080 px profile image, JPG or PNG

- [ ] Facebook banner, this can be an image 820 x 415 px or video 820 by 462 pixels with a video resolution of 1080p.

- [ ] Twitter banner image 1500 x 500 px, JPG or PNG
