### ISSUE TITLE
Launch Article #1

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opensourcedesign#25]
1st draft of the launch article due on the 21st/22nd of May for review via Lade

**Comment by deaduramilade** [comment]
Article outline done
https://docs.google.com/document/d/1opXZV26LaBvWn6gttXBkjq-JVmZGBI7Dw0sAcLvPy4g/edit?usp=sharing

**Comment by deaduramilade** [comment]
Article update https://docs.google.com/document/d/1zSdWCBxAkt8kNKFLAZt07FswpKnoiB0mb-rk0wFB_yg/edit?usp=sharing
