### ISSUE TITLE
Square logo to be created

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opensourcedesign#27]
We need a logo that will work on social icons/profiles that is square orientation. 

max size 1080x1080px - High res version in .png .jpg .svg

min size 50x50px low res version  .png .jpg .svg

Favicon .favi (use website to create this)

**Comment by Erioldoesdesign** [comment]
Files of square logos here in both 1080px and 50px

![Logo – square.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/ee2d8a10-83e6-44e1-b5e7-c47aebb2810b)
![Logo – square – 2.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/a857d354-ca23-49e7-b932-659dfa6fb3b3)
![Logo – square – 1.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/f89d7d5a-bb16-49fe-82b0-16a264733be8)

**Comment by Erioldoesdesign** [comment]
Favicon's here:

![favicon.ico](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/983bee80-ef4a-4f5f-b216-6ac581194d29)

![favicon.ico](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/35eac477-e660-4df6-af5e-8a1736e99fba)

**Comment by thesocialdetail** [comment]
Hi @aschwersenz,  here are Favicons I mentioned.

**Comment by Erioldoesdesign** [comment]
![favicon.ico](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/a8109b6e-8bc1-4422-a21f-64e44c48e4af)

@aschwersenz here's the .ico file you'll need
