### ISSUE TITLE
Create Twitter banner image

### ISSUE THREAD

**Issue by Erioldoesdesign** [ushahidi/opensourcedesign#35]
Twitter banner image 1500 x 500 px, JPG or PNG

**Comment by Erioldoesdesign** [comment]
Can you review these @thesocialdetail and see what you think?

![Twitter banner – 1.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/c3a3b32d-d5e2-4adb-828f-26d2f4101458)

![Twitter banner – 2.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/6cd50edc-7fa7-4192-b15c-179e94d34a03)

![Twitter-banner---3.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/415b8a90-ce30-4e3c-9bb3-60d8760bfc56)

**Comment by thesocialdetail** [comment]
Perfect.
