### ISSUE TITLE
Create Facebook banner

### ISSUE THREAD

**Issue by thesocialdetail** [ushahidi/opensourcedesign#36]
Facebook banner, this can be an image 820 x 415 px or video 820 by 462 pixels with a video resolution of 1080p.

**Comment by Erioldoesdesign** [comment]
Same with these @thesocialdetail if you can review and let me know if they work :)

![fb banner - 1.png](https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/8b608ab4-b649-44fe-a427-15734f449c89)![fb banner – 2.png]

(https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/438766c4-6d3d-4554-9596-3aea2f50c872)![fb banner – 3.png]

(https://images.zenhubusercontent.com/5a6a0d5a4b5806bc2bc44bb9/2feb2e5c-20fa-4308-94d5-98be9a6beb65)

**Comment by thesocialdetail** [comment]
Perfect, uploaded as a sliding banner on the page
