### ISSUE TITLE
Project one liner 

### ISSUE THREAD

**Issue by thesocialdetail** [ushahidi/opensourcedesign#48]
Mainly need this for the social media platform but thought it would be good to have a agree one line for all content. 

This is what I pulled from the 1st article 

"Design should be open for all.  A project to create accessible processes for designers to collaborate and contribute to open source software."

**Comment by thesocialdetail** [comment]
The Twitter bio is maximum 160 characters, you can use this tool to help https://www.lettercount.com/

**Comment by deaduramilade** [comment]
I think the line you pulled out works

**Comment by thesocialdetail** [comment]
Sweet.

**Comment by Erioldoesdesign** [comment]
We also have this as a longer explanation when we have more characters to play with: 

"The aim of Open Design is to create useful, easy to use, ethical products that have a social impact by using a collaborative multidisciplinary approach that engages designers from all over the world."
