### ISSUE TITLE
Write a brief for Designit

### ISSUE THREAD

**Issue by justinscherer** [ushahidi/opensourcedesign#9]

**Comment by Erioldoesdesign** [comment]
Rough notes from Design Internal meeting:

Planning the brief doc for Designit visual design work
It's a brief not requirements.

- 1st part: Generative identity system that we can use to create a lot of social visuals and other assets & basic branding. Logo, guidelines, font etc.

- Website: How is it going to grow? Simple. To start, creative based on the visual system, basic description of the program/project, Explain the methodology, a place for a blog/writing/content (of various media) Where content should live. Can also live other places like Medium etc. based on content strategy.
Accessible to us without learning something new buildable on CMS? And updatable by us.
Build a flexible enough set of page elements that.
Email template for newsletter

CTA: Gather people and sign them up via a piece of info to receive info on the next events or be updated.

Newsletter content? Who and how will this happen?

Optional: History of past Design Jams?

Audiences:
Adobe and people in Adobe (both employed and not employed e.g. volunteer/champions)
Different types of Designers emerging and then established
	Tool enthusiasts/veterans
	Learners/Newbies
Open web/source people/humanitarian type people
Design press/podcasts/influencers/conference speakers/publications
Students formal/informal
Remote work people
Creatives people that do design but don’t call themselves designer (developing countries)

Not much overlap in all these but where there is overlap there’s our key audience.
Bringing together disparate people in one place to do good via design.

- Content strategy should be part of the content person’s role. When do we want to hire by? Decide by 30th April. Start in May. 2nd week of May. 

https://blog.mozilla.org/opendesign/
https://www.gv.com/sprint/

**Comment by Erioldoesdesign** [comment]
# Refined brief & what to cover:

⋅⋅* Introductions Ushahidi & Designit
⋅⋅* Background of project including the two past events
⋅⋅* Aims of the project as a whole. What are we trying to tackle? (Impart implicit understanding of project)
⋅⋅* Ushahidi's past work in Humanitarian tech, TenFour origin story and other notable Ushahidi projects

## Brief

The Open Source Design project needs a generative identity system that we can use to create various visuals.This should include basic branding and guidelines, logo/mark/identity, font choices, iconography and could include UI systems, illustration style, Photography/Videography style, Written article/document layout, Merchandise, Email Newsletter template, Slide decks etc.

The identity must be accessible and inclusive by those with disabilities, of marginalised background and low-bandwidth internet.

This needs to appeal and engage our key audience of 'Designers' that can be segmented in to several potential categories:

⋅⋅* People working at Adobe and volunteers/champions of Adobe's products and brand (e.g. Adobe XD champions
⋅⋅* Emerging designers. Characterised as not having been in the industry for more than 2-3 years.
⋅⋅* Established. Characterised by 3+ years in the industry.
⋅⋅* Designers who are particularly enthusiastic about 'tooling'. Those who follow updates to 'software/tools' and new 'software/tools' and are invested in discussions around 'software/tools'.
⋅⋅* Designers who use software/tools in their everyday job and are interested but not 'deeply invested' in 'software/tools'
⋅⋅* Creatives or Designers who are interested and invested in the 'Open web' 'Open source' and 'Tech for good' 
⋅⋅* The design press, Design related podcasts, Designer influencers, Regular/Well-known conference speakers and healthy design publications (online & print)
⋅⋅* Students in formal education institutions globally
⋅⋅* Students informally learning design related skills with the view to become design professionals
⋅⋅* Designers that work remotely
⋅⋅* Creatives people that 'do design' but don’t call themselves designers (most likely to live and operate in developing countries outside of major cities)

Some of these audiences could overlap. You could find a Design tool enthusiast who is also actively involved in 'doing good with design' but this may be a rare combination.

It is also likely that the project will attract the attention of non-profit organisations and projects looking to have their projects part of Open Source Design contribution. We are not primarily serving these audiences but must be aware of the great need of many non-profit, Open Source initiative that can and will benefit from a robust and successful Open Source Design process and community.

The Open Source Design project will need an independent web presence (not hosted on another service e.g. Medium, Git pages) that functions as the main hub for content and information for interested members of the audience detailed above with the key call to action being: To gather designers and 'sign them up' via a method of their choice (email, social media etc.) to receive information and updates on the Open Source Design project. 

The web presence must be able to be maintained and updated by non-technical people (people with little to know back or front end coding knowledge)

The web presence must be built in a manner which allow it to grow in purpose and content. For example, we anticipate written article style content but through the project research, there may be a need for video or audio content.

The web presence must be accessible, inclusive and reflect a core value of Ushahidi's work where we aim to work with and amplify the voices of the marginalised globally.

The information and updates will likely include, but not be limited to:
⋅⋅* Information on where an event will be held and how to participate/get involved
⋅⋅* How to participate/get involved outside of an event
⋅⋅* Methodology and project structure updates/insights
⋅⋅* Wrap up from any events
⋅⋅* Sign posting to other relevant projects and work around Open Source Design
⋅⋅* The history and past events with Open Source Design & TenFour.

The web presence may leverage other platforms for promotion. For example, Medium as a place for written content. Twitter, instagram, linkedin and facebook for community out reach and visibility. Meet-up and eventbrite for event listings.

### Other notable projects:

https://blog.mozilla.org/opendesign/
https://www.gv.com/sprint/
https://discourse.opensourcedesign.net/
https://design-system.service.gov.uk/community/propose-a-component-or-pattern/
https://beta.nhs.uk/service-manual/
https://design.wikimedia.org/style-guide/design-principles.html
https://www.mediawiki.org/wiki/Micro_Design_Improvements
